GPU HW Counters via rocprofiler (#84)
* Initial support for GPU hardware counters

* Update find modules for roctracer and rocprofiler

- /opt/rocm/{rocprofiler,roctracer} path is deprecated so tweak search procedure

* Improve ConfigCPack for MPI

* Update rocprofiler

- rocm_metrics()
- minor cleanup

* Update rocm find modules

* declare rocm_metrics + call in omnitrace-avail

* relocate omnitrace-launch-compiler

* REALPATH and find_modules

* Examples cmake (may drop)

* omnitrace-avail

- hw_counter categories
- init rocm

* setenv updates for rocprofiler in library.cpp and dl.cpp

* get_rocm_events config

* gpu::hip_device_count()

* rocm_metrics returns hardware_counters::info

* - relocated library/components/roctracer_callbacks.* to library/roctracer.*
- relocated library/components/rocprofiler.* to library/rocprofiler.*
- cleaned up rocprofiler.hpp
- added perfetto output of rocprofiler
- added timemory output of rocprofiler
- renamed omni.roctracer thread to roctracer.hip
- added roctracer.hsa thread name
- updated timemory submodule to support std::variant
- updated timemory submodule to support = in config value
- updated timemory submodule to support standalone storage
- updated timemory submodule to support new hw counter apis
- updated timemory submodule to prevent label/description caching in data_tracker

* update omnitrace-avail info_type generation

* Update timemory submodule

* rocprofiler component

* cmake formatting

* omnitrace-avail handle no GPUs

- Add -c command-line option for --categories
- support verbosity

* hsa_rsrc_factory throws exceptions

- throw exceptions to avoid aborting on HSA_STATUS_ERROR_NOT_INITIALIZED when advantageous
- removed duplicate specialization of is_available for component::rocprofiler

* rocprofiler symbols for when disabled

* Fix warning in omnitrace-avail

- std::stringstream from initializer list would use explicit constructor

* Fix finalization after settings are deleted

* Reorganized rocprofiler source

* Updated formatting

* Miscellaneous tweaks

- added using statements from timemory
- tweaked the main and thread bundle names
- fixed timemory header includes

diff --git a/.github/workflows/formatting.yml b/.github/workflows/formatting.yml
--- a/.github/workflows/formatting.yml
+++ b/.github/workflows/formatting.yml
@@ -74,7 +74,7 @@ jobs:
     - name: clang-format
       run: |
         set +e
-        FILES=$(find include src examples -type f | egrep '\.hpp$|\.cpp$|\.cpp\.in$')
+        FILES=$(find source examples -type f | egrep '\.hpp$|\.cpp$|\.cpp\.in$')
         FORMAT_OUT=$(clang-format-11 -output-replacements-xml ${FILES})
         RET=$(echo ${FORMAT_OUT} | grep -c '<replacement ')
         if [ "${RET}" -ne 0 ]; then
@@ -82,4 +82,22 @@ jobs:
           clang-format-11 -i ${FILES}
           git diff
           exit ${RET}
+        fi
+
+  includes:
+    runs-on: ubuntu-20.04
+
+    steps:
+    - uses: actions/checkout@v2
+    - name: check-includes
+      run: |
+        set +e
+        FILES=$(find source examples -type f | egrep '\.hpp$|\.cpp$|\.cpp\.in$')
+        MATCHES=$(egrep 'include "timemory|include <bits' ${FILES})
+        if [ -n "${MATCHES}" ]; then
+          echo -e "\nError! Included timemory header with quotes or bits folder included\n"
+          echo -e "### MATCHES: ###"
+          echo -e "${MATCHES}"
+          echo -e "################"
+          exit 1
         fi
